application: collardata1
version: 20100510
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /updater/.*
  script: updater.py

- url: /news/.*
  static_files: static/blank.html
  upload: static/blank.html

- url: /db/.*
  script: collardb.py

- url: /owners/.*
  script: owners.py

- url: /removesub/.*
  script: removesub.py

- url: /dist/.*
  script: dist.py

- url: /cleanup/.*
  script: cleanup.py

- url: /remote/.*
  script: remote_stub.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin

- url: /freebielist/.*
  script: freebielist.py
  login: admin

- url: /textureserver/.*
  script: textureserver.py

- url: /alarm/.*
  script: alarm.py

- url: /wiki_redirect/.*
  script: wiki_redirect.py

- url: /avsync/.*
  script: avsync.py

- url: /groupname/.*
  script: groupname.py

admin_console:
  pages:
  - name: Admin Console
    url: /admin/
  - name: Stats
    url: /stats/